# .github/workflows/build.yml
name: Build Forge 1.16.5 (matrix)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gradleVersion: [ '7.5.1', '7.6.4' ]
        fgVersion:     [ '5.1.57', '6.0.9' ]
    fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Update Gradle wrapper to ${{ matrix.gradleVersion }}
        run: ./gradlew wrapper --gradle-version ${{ matrix.gradleVersion }}

      - name: Patch ForgeGradle plugin to ${{ matrix.fgVersion }}
        run: |
          sed -i \
            's|id("net.minecraftforge.gradle").*|id("net.minecraftforge.gradle") version "${{ matrix.fgVersion }}"|' \
            loader/forge/fml36/build.gradle.kts

      - name: Make wrapper executable
        run: chmod +x gradlew

      - name: Build Forge module
        run: ./gradlew :loader-forge-fml36:build
        continue-on-error: true

      - name: Upload successful JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: forge-1.16.5-jar-${{ matrix.gradleVersion }}-${{ matrix.fgVersion }}
          path: loader/forge/fml36/build/libs/*.jar
